# Generated by Django 5.1.5 on 2025-01-19 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaregiverPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='CaregiverType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='caregiver_types/')),
            ],
        ),
        migrations.CreateModel(
            name='CaregiverPackageList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='package_lists/')),
                ('name', models.CharField(max_length=255)),
                ('caregiver_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_lists', to='caregiver.caregiverpackage')),
            ],
        ),
        migrations.AddField(
            model_name='caregiverpackage',
            name='caregiver_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='caregiver.caregivertype'),
        ),
    ]
