# Generated by Django 5.1.5 on 2025-01-19 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthpackage',
            name='descriptionTwo',
            field=models.CharField(default='Default Description', max_length=355),
        ),
        migrations.AddField(
            model_name='healthpackage',
            name='reason',
            field=models.CharField(default='Default Reason', max_length=255),
        ),
    ]
