# Generated by Django 5.1.5 on 2025-01-19 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_healthpackage_descriptiontwo_healthpackage_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthpackage',
            name='descriptionTwo',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='healthpackage',
            name='reason',
            field=models.CharField(max_length=255),
        ),
    ]
